version: "3.8"
services:
  web:
    build: .
    container_name: ctf_race_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
